#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

# reject commit-ing in "release" branch
branch=`git symbolic-ref HEAD --short`
if [ ${branch} = release ]; then
  cat <<\EOF
  エラー：releaseブランチにcommitはできません。
EOF
    exit 1
fi
