name: Deploy Website to S3

on:
  push:
    tags:
      - v*

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - name: Checkout
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
        with:
          persist-credentials: false
      - uses: aws-actions/configure-aws-credentials@e7f100cf4c008499ea8adda475de1042d6975c7b # v6.2.0
        with:
          aws-region: 'ap-northeast-1'
          role-to-assume: 'arn:aws:iam::607167088920:role/github-actions'
      - name: Install, build, and upload your site
        uses: withastro/action@b7d53628f8b666036b0238aadb0b984a2a489f26 # v6.1.1
        env:
          NOTION_API_SECRET: ${{ secrets.NOTION_API_SECRET }}
          DATABASE_ID: ${{ secrets.DATABASE_ID }}
      - name: Deploy to S3
        run: aws s3 sync ./dist/ s3://${{ secrets.BUCKET_ID }}
      - name: Create CloudFront invalidation
        run: aws cloudfront create-invalidation --distribution-id ${{ secrets.DISTRIBUTION_ID }} --paths "/*"
