name: Deploy Amplify to development

on:
  pull_request:
    branches:
      - main
    types: [opened, reopened]

jobs:
  amplify-for-dev:
    runs-on: ubuntu-latest
    if: >-
      ! contains(github.event.pull_request.title, '[dreamkast-releasebot]') &&
      ! contains(github.event.pull_request.labels.*.name, 'dependencies')
    steps:
      - uses: actions/checkout@v2

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Set BRANCH
        id: set-branchname
        run: |
          # for debug
          echo REF ${{ github.ref }}
          echo HEAD REF ${{ github.head_ref }}
          echo SHA ${{ github.sha }}

          # get branch name
          if [ ! -e ${{ github.head_ref }} ]; then
            BRANCH=${{ github.head_ref }}
          else
            BRANCH=$(echo "${{ github.ref }}" | sed -e 's|.*/\(.*\)|\1|')
          fi

          echo "::set-output name=BRANCH::${BRANCH}"

      - name: Deploy preview-app
        uses: yinlinchen/amplify-preview-actions@v1.1
        with:
          branch_name: ${{ steps.set-branchname.outputs.BRANCH }}
          amplify_command: deploy
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AmplifyAppId: ${{ secrets.AMPLIFYAPPID }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
          BackendEnvARN: ${{ secrets.BACKEND_ARN_DEV }}

      - name: Get Amplify App's default domain
        id: default-domain
        run: |
          DEFAULT_DOMAIN=$(aws amplify --region ${{ secrets.AWS_REGION }} get-app --app-id ${{ secrets.AMPLIFYAPPID }} | jq -cr '.app.defaultDomain')
          echo $DEFAULT_DOMAIN
          echo "::set-output name=DOMAIN::${DEFAULT_DOMAIN}"

      - name: Create comment
        uses: peter-evans/create-or-update-comment@v1
        if: ${{ github.event.action == 'opened' }}
        with:
          issue-number: ${{ github.event.pull_request.number }}
          body: |
            Amplify Console
            https://${{ secrets.AWS_REGION }}.console.aws.amazon.com/amplify/home?region=${{ secrets.AWS_REGION }}#/${{ secrets.AMPLIFYAPPID }}

            Website
            https://${{ steps.set-branchname.outputs.BRANCH }}.${{ steps.default-domain.outputs.DOMAIN }}/
